echo "=== SWAN_V3 ALL part2 started ==="

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.6, "target_mask_density": 0.32, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.6, "target_mask_density": 0.32, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.6, "target_mask_density": 0.32, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.6, "target_mask_density": 0.32, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 1, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 1, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 3, "horizon": 96, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 3, "horizon": 192, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 3, "horizon": 336, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 3, "horizon": 720, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 2, "horizon": 192, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 2, "horizon": 336, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTm2.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 1, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.2, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTm2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.08, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.2, "target_mask_density": 0.4, "density_lambda": 0.1, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.08, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.2, "target_mask_density": 0.4, "density_lambda": 0.1, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.08, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.2, "target_mask_density": 0.4, "density_lambda": 0.1, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.08, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.2, "target_mask_density": 0.4, "density_lambda": 0.1, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.2, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.2, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.2, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Traffic.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.2, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Traffic/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 2, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 2, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Exchange.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 512, "d_model": 256, "dropout": 0.3, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Exchange/SWAN_V3"


echo "=== SWAN_V3 ALL part2 finished ==="
