#!/usr/bin/env bash
set -e

echo "=== SWAN_V3 maize_NL_NL11_daily_meteo_plus_targets TUNE_R4 started ==="

# R4 目标：
# 1) h24: 在 C2 附近做更细 density_lambda/轻正则搜索
# 2) h48: 在 C3 附近细调 dropout + lr + density_lambda
# 3) h96: 在 D4 附近继续低学习率长训练，并增加 1 组 seed 稳健性验证

DATA_NAME="maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv"

# -----------------------------
# h24: around R3 best h24_C2
# -----------------------------

# h24_D1: R3 best 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.045, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h24_D1"

# h24_D2: 更弱稀疏约束
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.042, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h24_D2"

# h24_D3: 更强稀疏约束
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.048, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h24_D3"

# h24_D4: 轻正则（dropout）+ 略高掩码密度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.045, "dropout": 0.01, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.57, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h24_D4"

# -----------------------------
# h48: around R3 best h48_C3
# -----------------------------

# h48_D1: R3 best 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.02, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h48_D1"

# h48_D2: 稍弱正则
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.015, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h48_D2"

# h48_D3: 降 lr + 增训练轮数（收敛细化）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.052, "dropout": 0.02, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00022, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 160, "patch_len": 8, "patience": 25, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 130, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 650, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h48_D3"

# -----------------------------
# h96: around R3 best h96_D4
# -----------------------------

# h96_E1: R3 best 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h96_E1"

# h96_E2: 更低学习率 + 更长训练
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00018, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 200, "patch_len": 8, "patience": 35, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 160, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 750, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h96_E2"

# h96_E3: 略强稀疏 + 适中学习率
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.052, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00022, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 145, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h96_E3"

# h96_E4: 轻降 dropout + 略增掩码密度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.048, "dropout": 0.04, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 145, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.47, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h96_E4"

# h96_E5: seed 稳健性验证（参数同 E1）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1], "seed": 2027}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R4/h96_E5"

echo "=== SWAN_V3 maize_NL_NL11_daily_otb_meteo_plus_targets TUNE_R4 finished ==="
