echo "=== SWAN grid stage1 started ==="

# -------------------------------
# Grid profile A: conservative sparsity
# -------------------------------
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage1"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage1"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage1"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage1"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage1"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage1"

# -------------------------------
# Grid profile B: stronger sparsity
# -------------------------------
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage1"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage1"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage1"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage1"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage1"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage1"

echo "=== SWAN grid stage1 finished ==="
