echo "=== SWAN_V3 ALL part1 started ==="

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.1, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.45, "density_lambda": 0.12, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02, "lambda3": 0.004, "weight_threshold": 0.07, "mask_sparsity_lambda": 0.0003}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.1, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.45, "density_lambda": 0.12, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02, "lambda3": 0.006, "weight_threshold": 0.08, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.7, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "PJM.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.7, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "PJM/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.7, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "BE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.7, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "BE/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "FR.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "FR/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.7, "batch_size": 64, "d_ff": 64, "d_model": 128, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "DE.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.7, "batch_size": 64, "d_ff": 64, "d_model": 128, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "DE/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.6, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Energy.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.6, "batch_size": 64, "d_ff": 256, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Energy/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.3, "batch_size": 64, "d_ff": 64, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.3, "batch_size": 64, "d_ff": 64, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfm2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfm2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.05, "batch_size": 64, "d_ff": 64, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh1.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.05, "batch_size": 64, "d_ff": 64, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh1/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.05, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 168, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Sdwpfh2.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.05, "batch_size": 64, "d_ff": 512, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 720, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Sdwpfh2/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 64, "d_model": 128, "dropout": 0.0, "e_layers": 1, "horizon": 10, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 30, "patience": 5, "seq_len": 60, "stride": 30, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Colbun.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.9, "batch_size": 64, "d_ff": 64, "d_model": 128, "dropout": 0.0, "e_layers": 1, "horizon": 30, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 30, "patience": 5, "seq_len": 180, "stride": 30, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Colbun/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.6, "batch_size": 64, "d_ff": 64, "d_model": 128, "dropout": 0.0, "e_layers": 1, "horizon": 10, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 60, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Rapel.csv" --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.6, "batch_size": 64, "d_ff": 64, "d_model": 128, "dropout": 0.0, "e_layers": 1, "horizon": 30, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "seq_len": 180, "stride": 8, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Rapel/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 16, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 16, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 16, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SWAN_V3"

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Electricity.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.5, "batch_size": 16, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "adaptive_alpha": true, "alpha_hidden": 16, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0, "freq_use_phase": true, "phase_weight": 0.3, "target_mask_density": 0.35, "density_lambda": 0.08, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Electricity/SWAN_V3"

echo "=== SWAN_V3 ALL part1 finished ==="