#!/usr/bin/env bash
set -e

echo "=== SWAN_V3 maize_NL_NL11_daily_meteo_plus_targets TUNE_R3 started ==="

# 基于 R2 最优点进行局部精调：
# - h24 围绕 B2（当前最优）
# - h48 同时兼顾 mse（B3）与 mae（B2）
# - h96 围绕 C3（当前显著最优）做稳健化搜索

DATA_NAME="maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv"

# -----------------------------
# h24: around R2 best h24_B2
# -----------------------------

# h24_C1: R2 best 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h24_C1"

# h24_C2: 轻微降低稀疏强度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.045, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h24_C2"

# h24_C3: 降学习率 + 降掩码密度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h24_C3"

# h24_C4: 稀疏略强 + 降掩码密度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h24_C4"

# -----------------------------
# h48: around R2 best h48_B3
# -----------------------------

# h48_C1: R2 mae-优 (B2) 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h48_C1"

# h48_C2: R2 mse-优 (B3) 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.06, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h48_C2"

# h48_C3: mse/mae 折中
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.02, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h48_C3"

# -----------------------------
# h96: around R2 best h96_C3
# -----------------------------

# h96_D1: R2 best 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.06, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 160, "patch_len": 8, "patience": 25, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h96_D1"

# h96_D2: 降 dropout，测试欠拟合/过正则平衡
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.03, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 160, "patch_len": 8, "patience": 25, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h96_D2"

# h96_D3: 提高掩码密度，增强可学信息
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.06, "dropout": 0.03, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 160, "patch_len": 8, "patience": 25, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h96_D3"

# h96_D4: 更长训练 + 更低学习率
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R3/h96_D4"

echo "=== SWAN_V3 maize_NL_NL11_daily_otb_meteo_plus_targets TUNE_R3 finished ==="
