echo "=== SWAN_V2 stage4 started ==="

# ------------------------------------------------------------
# ETTh1: 短期与长期分开验证（v2核心改动收益）
# ------------------------------------------------------------
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v2.SWANV2" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "freq_use_phase": true, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V2_stage4"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v2.SWANV2" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "weight_gate_sharpness": 8.0, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0, "freq_use_phase": true, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V2_stage4"

# ------------------------------------------------------------
# Weather: v2重点验证（logit融合+相位特征+动态稀疏）
# ------------------------------------------------------------
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v2.SWANV2" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "weight_gate_sharpness": 8.0, "mask_tau_init": 5.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.88, "mask_sparsity_lambda": 0.0005, "freq_use_phase": true, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_V2_stage4"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v2.SWANV2" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "weight_gate_sharpness": 8.0, "mask_tau_init": 5.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.88, "mask_sparsity_lambda": 0.0005, "freq_use_phase": true, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_V2_stage4"

# ------------------------------------------------------------
# NP: 短/长周期回补验证
# ------------------------------------------------------------
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v2.SWANV2" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.006, "lambda3_warmup_steps": 500, "weight_threshold": 0.08, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "freq_use_phase": true, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_V2_stage4"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v2.SWANV2" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.008, "lambda3_warmup_steps": 500, "weight_threshold": 0.09, "weight_tau_init": 1.1, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.0015, "freq_use_phase": true, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_V2_stage4"

echo "=== SWAN_V2 stage4 finished ==="
