echo "=== SWAN grid stage3 started ==="

# ------------------------------------------------------------
# ETTh1-96: 以stage2-C2为中心做局部搜索（追平/超越DAG短期）
# ------------------------------------------------------------
# E96-A: mild sparsity
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.0025, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.84, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage3"
# E96-B: balanced sparsity
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.86, "mask_sparsity_lambda": 0.0007}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage3"
# E96-C: slightly stronger sparsity
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.004, "lambda3_warmup_steps": 500, "weight_threshold": 0.07, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.88, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage3"

# ------------------------------------------------------------
# Weather-96/720: 以stage2-C1为基线，微调通道稀疏与融合权重
# ------------------------------------------------------------
# W-A: baseline-like
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage3"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage3"

# W-B: lower mask penalty, slightly higher residual retention
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.88, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage3"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.88, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage3"

# W-C: tune fusion toward temporal branch
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.55, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage3"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.55, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage3"

# ------------------------------------------------------------
# NP-360: 围绕stage2-C1继续回补（重点改善长周期）
# ------------------------------------------------------------
# N360-A: stronger mask selectivity
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 4.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.92, "mask_sparsity_lambda": 0.002}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage3"
# N360-B: medium selectivity + smoother anneal
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.008, "lambda3_warmup_steps": 500, "weight_threshold": 0.09, "weight_tau_init": 1.1, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.0015}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage3"
# N360-C: keep residual path stronger, reduce mask penalty slightly
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.008, "lambda3_warmup_steps": 500, "weight_threshold": 0.09, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.88, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage3"

echo "=== SWAN grid stage3 finished ==="
