#!/usr/bin/env bash
set -e

echo "=== SWAN_V3 maize_NL_NL11_daily_targets_only TUNE_R1 started ==="

# 数据文件：dataset/forecasting/maize_NL_NL11_daily_otb_targets_only.csv
# OTB 顺序为 ssm -> rsm，因此 target_channel=-1 对应 rsm
# 目标：在 SWAN_V3_BASE 基础上进一步优化 h12/h24/h48 的 mse_norm 与 mae_norm

# h12-A: 稳定化短期（轻降学习率 + 稍降稀疏强度）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_targets_only.csv" --strategy-args '{"horizon": 12, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.03, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 12, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_targets_only/SWAN_V3_TUNE_R1/maize_h12_A"

# h12-B: 增大 patch 覆盖 1~2 周局部结构
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_targets_only.csv" --strategy-args '{"horizon": 12, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.03, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 12, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 12, "patience": 20, "phase_weight": 0.25, "seq_len": 120, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 6, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_targets_only/SWAN_V3_TUNE_R1/maize_h12_B"

# h24-A: 中期主力（更细 patch + 适中稀疏）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_targets_only.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.03, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 12, "patience": 20, "phase_weight": 0.25, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 6, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_targets_only/SWAN_V3_TUNE_R1/maize_h24_A"

# h24-B: 增长上下文窗口，捕捉月内变化
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_targets_only.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.03, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 16, "patience": 20, "phase_weight": 0.25, "seq_len": 240, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_targets_only/SWAN_V3_TUNE_R1/maize_h24_B"

# h48-A: 维持长周期优势（更长 patch）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_targets_only.csv" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.03, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 16, "patience": 20, "phase_weight": 0.25, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_targets_only/SWAN_V3_TUNE_R1/maize_h48_A"

# h48-B: 更长上下文，验证是否继续获益
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_targets_only.csv" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.03, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 24, "patience": 20, "phase_weight": 0.25, "seq_len": 480, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 12, "target_mask_density": 0.50, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_targets_only/SWAN_V3_TUNE_R1/maize_h48_B"

echo "=== SWAN_V3 maize_NL_NL11_daily_targets_only TUNE_R1 finished ==="
