echo "=== SWAN grid stage2 started ==="

# ---------------------------------------------
# ETTh1: stage1中 Profile A 更优，围绕A做局部细化
# ---------------------------------------------
# ETTh1-C1: 复用stage1最优(A)
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage2"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.002, "lambda3_warmup_steps": 500, "weight_threshold": 0.05, "weight_tau_init": 1.5, "weight_tau_min": 0.5, "weight_tau_decay": 0.9995, "mask_tau_init": 8.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9995, "mask_residual_beta": 0.8, "mask_sparsity_lambda": 0.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage2"

# ETTh1-C2: 在A基础上略增强稀疏与掩码强度，测试是否可进一步提升短期
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage2"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.95, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_grid_stage2"

# ---------------------------------------------
# Weather: stage1中 Profile B 更优，围绕B做局部细化
# ---------------------------------------------
# Weather-C1: 复用stage1最优(B)
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage2"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage2"

# Weather-C2: 略增强稀疏，验证中长周期是否继续收益
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.015, "lambda3_warmup_steps": 500, "weight_threshold": 0.12, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 4.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.92, "mask_sparsity_lambda": 0.002}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage2"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "Weather.csv" --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.5, "beta": 0.1, "batch_size": 32, "d_ff": 512, "d_model": 256, "dropout": 0.0, "e_layers": 1, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.015, "lambda3_warmup_steps": 500, "weight_threshold": 0.12, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 4.5, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.92, "mask_sparsity_lambda": 0.002}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "Weather/SWAN_grid_stage2"

# ---------------------------------------------
# NP: stage1中 Profile B 略优，但与DAG仍有差距，做“回补型”细化
# ---------------------------------------------
# NP-C1: 复用stage1最优(B)
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage2"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.01, "lambda3_warmup_steps": 500, "weight_threshold": 0.1, "weight_tau_init": 1.0, "weight_tau_min": 0.5, "weight_tau_decay": 0.999, "mask_tau_init": 5.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.999, "mask_residual_beta": 0.9, "mask_sparsity_lambda": 0.001}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage2"

# NP-C2: 降低阈值与正则，增加残差保真，尝试减少过稀疏造成的信息损失
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 168, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.006, "lambda3_warmup_steps": 500, "weight_threshold": 0.08, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage2"
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "NP.csv" --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan.SWAN" --model-hyper-params '{"alpha": 0.9, "beta": 0.1, "batch_size": 64, "d_ff": 128, "d_model": 64, "dropout": 0.0, "e_layers": 1, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "seq_len": 720, "stride": 48, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.006, "lambda3_warmup_steps": 500, "weight_threshold": 0.08, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "NP/SWAN_grid_stage2"

echo "=== SWAN grid stage2 finished ==="
