echo "=== SWAN_V3 stage5 debug started ==="

# 说明：
# 1) 仅跑 ETTh1-96，快速定位 NaN 来源
# 2) 按 A -> E 逐步开启 v3 新机制
# 3) 结果统一保存到 ETTh1/SWAN_V3_stage5_debug

# A: 最小稳定基线（尽量贴近 v2，不开 v3 新机制）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "adaptive_alpha": false, "alpha_hidden": 16, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "weight_gate_floor": 0.0, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "target_mask_density": 0.35, "density_lambda": 0.0, "freq_use_phase": false, "phase_weight": 0.0, "dynamic_sparse": false, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3_stage5_debug"

# B: 只开启 phase（验证频域相位引入是否导致数值问题）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "adaptive_alpha": false, "alpha_hidden": 16, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "weight_gate_floor": 0.0, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "target_mask_density": 0.35, "density_lambda": 0.0, "freq_use_phase": true, "phase_weight": 0.2, "dynamic_sparse": false, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3_stage5_debug"

# C: 在 B 基础上开启 gate_floor（验证门控保底影响）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "adaptive_alpha": false, "alpha_hidden": 16, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "weight_gate_floor": 0.05, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "target_mask_density": 0.35, "density_lambda": 0.0, "freq_use_phase": true, "phase_weight": 0.2, "dynamic_sparse": false, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3_stage5_debug"

# D: 在 C 基础上开启 adaptive_alpha（验证自适应融合）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "adaptive_alpha": true, "alpha_hidden": 16, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "weight_gate_floor": 0.05, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "target_mask_density": 0.35, "density_lambda": 0.0, "freq_use_phase": true, "phase_weight": 0.2, "dynamic_sparse": false, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3_stage5_debug"

# E: 全量 v3（再开启 dynamic_sparse + density）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "ETTh1.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"alpha": 0.95, "adaptive_alpha": true, "alpha_hidden": 16, "beta": 0.1, "batch_size": 64, "d_ff": 512, "d_model": 1024, "dropout": 0.1, "e_layers": 2, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "seq_len": 96, "stride": 24, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "lambda3": 0.003, "lambda3_warmup_steps": 500, "weight_threshold": 0.06, "weight_tau_init": 1.2, "weight_tau_min": 0.5, "weight_tau_decay": 0.9993, "weight_gate_sharpness": 8.0, "weight_gate_floor": 0.05, "mask_tau_init": 6.0, "mask_tau_min": 0.5, "mask_tau_decay": 0.9993, "mask_residual_beta": 0.85, "mask_sparsity_lambda": 0.0005, "target_mask_density": 0.35, "density_lambda": 0.1, "freq_use_phase": true, "phase_weight": 0.2, "dynamic_sparse": true, "sparse_warmup_steps": 500, "sparse_plateau_patience": 100, "sparse_beta_min": 0.2, "sparse_beta_max": 1.0, "sparse_step_up": 0.05, "sparse_step_down": 0.02}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "ETTh1/SWAN_V3_stage5_debug"

echo "=== SWAN_V3 stage5 debug finished ==="
