#!/usr/bin/env bash
set -e

echo "=== SWAN_V3 FINAL started ==="
python ./scripts/covariate_forecasting/update_swan_v3_final_compare_html.py

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list BE.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.7, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path BE/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list BE.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.7, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path BE/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Colbun.csv --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 128, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 10, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 80, "patch_len": 30, "patience": 10, "phase_weight": 0.15, "seq_len": 60, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 200, "stride": 30, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Colbun/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Colbun.csv --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 128, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 30, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 30, "patience": 5, "phase_weight": 0.3, "seq_len": 180, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 30, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Colbun/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list DE.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.7, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 128, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "phase_weight": 0.3, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path DE/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list DE.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.7, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 128, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 10, "phase_weight": 0.2, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path DE/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh1.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.95, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 1024, "density_lambda": 0.06, "dropout": 0.1, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.45, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.4, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.04, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh1.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.95, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 1024, "density_lambda": 0.08, "dropout": 0.1, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.6, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.32, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh1.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.95, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 1024, "density_lambda": 0.06, "dropout": 0.1, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.45, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.4, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.04, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh1.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.95, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 1024, "density_lambda": 0.08, "dropout": 0.1, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 2, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.6, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.32, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh2.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.04, "dropout": 0.2, "dynamic_sparse": false, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh2.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.2, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh2.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.04, "dropout": 0.2, "dynamic_sparse": false, "e_layers": 1, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTh2.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.04, "dropout": 0.2, "dynamic_sparse": false, "e_layers": 1, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTh2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm1.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 3, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm1.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 3, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm1.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 3, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm1.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.06, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 3, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 1e-05, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.45, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.4, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.04, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm2.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.2, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm2.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.2, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm2.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.04, "dropout": 0.2, "dynamic_sparse": false, "e_layers": 2, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list ETTm2.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.04, "dropout": 0.2, "dynamic_sparse": false, "e_layers": 2, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 12, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path ETTm2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Electricity.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 16, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Electricity/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Electricity.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 16, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Electricity/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Electricity.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 16, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Electricity/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Electricity.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 16, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Electricity/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Energy.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 10, "phase_weight": 0.2, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Energy/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Energy.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 10, "phase_weight": 0.2, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Energy/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Exchange.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Exchange/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Exchange.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Exchange/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Exchange.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Exchange/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Exchange.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.3, "dynamic_sparse": true, "e_layers": 2, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 16, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Exchange/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list FR.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 10, "phase_weight": 0.2, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path FR/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list FR.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "phase_weight": 0.3, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path FR/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list NP.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 128, "d_model": 64, "density_lambda": 0.12, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "lambda3": 0.004, "loss": "MAE", "lr": 0.001, "lradj": "type3", "mask_sparsity_lambda": 0.0003, "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "phase_weight": 0.3, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.1, "weight_gate_sharpness": 8.0, "weight_threshold": 0.07}' --gpus 0 --num-workers 1 --timeout 60000 --save-path NP/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list NP.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.9, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 128, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 32, "patience": 10, "phase_weight": 0.2, "seq_len": 960, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 32, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path NP/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list PJM.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.7, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 48, "patience": 5, "phase_weight": 0.3, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path PJM/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list PJM.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.7, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type1", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 10, "phase_weight": 0.2, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path PJM/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Rapel.csv --strategy-args '{"horizon": 10, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 128, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 10, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 60, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Rapel/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Rapel.csv --strategy-args '{"horizon": 30, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 128, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 30, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 180, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Rapel/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfh1.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.05, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfh1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfh1.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.05, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 64, "density_lambda": 0.04, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 8, "patience": 12, "phase_weight": 0.15, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 300, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfh1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfh2.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.05, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 64, "density_lambda": 0.04, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 8, "patience": 12, "phase_weight": 0.15, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 300, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfh2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfh2.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.05, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 64, "density_lambda": 0.04, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 8, "patience": 12, "phase_weight": 0.15, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 300, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfh2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfm1.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.3, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfm1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfm1.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.3, "alpha_hidden": 16, "batch_size": 64, "d_ff": 64, "d_model": 64, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 8, "patience": 5, "phase_weight": 0.3, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfm1/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfm2.csv --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 64, "density_lambda": 0.04, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 12, "phase_weight": 0.15, "seq_len": 168, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 300, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfm2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Sdwpfm2.csv --strategy-args '{"horizon": 360, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.1, "alpha_hidden": 16, "batch_size": 64, "d_ff": 512, "d_model": 64, "density_lambda": 0.04, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 360, "loss": "MAE", "lr": 0.001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 48, "patience": 12, "phase_weight": 0.15, "seq_len": 720, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 300, "stride": 48, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Sdwpfm2/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Traffic.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.2, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Traffic/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Traffic.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.2, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Traffic/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Traffic.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.2, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.08, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.3, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.35, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.05, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Traffic/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Traffic.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.2, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Traffic/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Weather.csv --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.1, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 80, "patch_len": 24, "patience": 8, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Weather/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Weather.csv --strategy-args '{"horizon": 192, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 192, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Weather/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Weather.csv --strategy-args '{"horizon": 336, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.1, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 336, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 50, "patch_len": 24, "patience": 5, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "target_mask_density": 0.4, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.08, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Weather/SWAN_V3_FINAL

python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list Weather.csv --strategy-args '{"horizon": 720, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.5, "alpha_hidden": 16, "batch_size": 32, "d_ff": 512, "d_model": 256, "density_lambda": 0.05, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 720, "loss": "MAE", "lr": 0.0001, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 100, "patch_len": 24, "patience": 10, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 24, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path Weather/SWAN_V3_FINAL

echo "=== SWAN_V3 FINAL finished ==="
