#!/usr/bin/env bash
set -e

echo "=== SWAN_V3 maize_NL_NL11_daily_meteo_plus_targets TUNE_R5 started ==="

# R5 目标：
# 1) h24: 围绕 R4 最优 D4（0.03164）继续细调 target_mask_density
# 2) h48: 在 D1(mse优) 与 D2(mae优)之间做折中
# 3) h96: 回到 R3 D4 邻域做微调，并补充 seed 稳健性验证

DATA_NAME="maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv"

# -----------------------------
# h24: around R4 best h24_D4
# -----------------------------

# h24_E1: R4 best 复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.045, "dropout": 0.01, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.57, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h24_E1"

# h24_E2: 略降掩码密度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.045, "dropout": 0.01, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.56, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h24_E2"

# h24_E3: 略升掩码密度
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.045, "dropout": 0.01, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.58, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h24_E3"

# h24_E4: 轻微下调密度lambda
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.044, "dropout": 0.01, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.57, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h24_E4"

# -----------------------------
# h48: around R4 best h48_D1
# -----------------------------

# h48_E1: R4 mse-最优复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.02, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h48_E1"

# h48_E2: R4 mae-更优点复现
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.055, "dropout": 0.015, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h48_E2"

# h48_E3: 折中微调（dropout 与 lr）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.054, "dropout": 0.017, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.00024, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.5, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h48_E3"

# -----------------------------
# h96: around current best h96_D4
# -----------------------------

# h96_F1: 当前最优复现（R3 D4）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h96_F1"

# h96_F2: 轻微降低稀疏惩罚
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.049, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h96_F2"

# h96_F3: 轻微降低 dropout
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.045, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h96_F3"

# h96_F4: 更低学习率 + 略长训练
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.051, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00019, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 190, "patch_len": 8, "patience": 32, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 150, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 720, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h96_F4"

# h96_F5: seed 稳健性验证（参数同 F1）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "$DATA_NAME" --strategy-args '{"horizon": 96, "target_channel": [-1], "seed": 2028}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.05, "dropout": 0.05, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0002, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 180, "patch_len": 8, "patience": 30, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 140, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 700, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R5/h96_F5"

echo "=== SWAN_V3 maize_NL_NL11_daily_otb_meteo_plus_targets TUNE_R5 finished ==="
