#!/usr/bin/env bash
set -e

echo "=== SWAN_V3 maize_NL_NL11_daily_meteo_plus_targets TUNE_R1 started ==="

# 数据文件（已预处理）
# dataset/forecasting/maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv
# 特征顺序：tmin,tmax,tavg,prec,rad,et0,cwb,ssm,rsm
# target_channel=-1 对应 rsm
# 目标：定位 meteo 特征在中长 horizon 的有效性，重点优化 h24/h48，并探索 h96

# h12-A: 当前最优结构对照组（用于确认短期收益稳定）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 12, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 12, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 96, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h12_A"

# h24-A: 全外生（当前 meteo 基线）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h24_A"

# h24-B: 仅保留 covariate 外生（去时间外生）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h24_B"

# h24-C: 仅保留时间外生（去 covariate 外生）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 0, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h24_C"

# h24-D: 去全部外生（只用目标通道）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 24, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 24, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 192, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 0, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h24_D"

# h48-A: 全外生（当前 meteo 基线）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h48_A"

# h48-B: 仅保留 covariate 外生
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h48_B"

# h48-C: 仅保留时间外生
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 0, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h48_C"

# h48-D: 去全部外生
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 48, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 48, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 384, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 0, "use_t": 1, "use_t_exog": 0, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h48_D"

# h96-A: 长期基线（全外生）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.04, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.0003, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 120, "patch_len": 8, "patience": 15, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 100, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 500, "stride": 8, "target_mask_density": 0.55, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h96_A"

# h96-B: 长期稳健化（增强稀疏约束 + 降掩码密度）
python ./scripts/run_benchmark.py --config-path "rolling_forecast_config.json" --data-name-list "maize_NL_NL11_daily_otb_meteo_plus_targets_filled.csv" --strategy-args '{"horizon": 96, "target_channel": [-1]}' --model-name "swan_v3.SWANV3" --model-hyper-params '{"adaptive_alpha": true, "alpha": 0.6, "alpha_hidden": 16, "batch_size": 64, "d_ff": 256, "d_model": 64, "density_lambda": 0.06, "dropout": 0.0, "dynamic_sparse": true, "e_layers": 1, "freq_use_phase": true, "horizon": 96, "loss": "MAE", "lr": 0.00025, "lradj": "type3", "n_heads": 4, "norm": true, "num_epochs": 140, "patch_len": 8, "patience": 20, "phase_weight": 0.2, "seq_len": 768, "sparse_beta_max": 1.0, "sparse_beta_min": 0.2, "sparse_plateau_patience": 120, "sparse_step_down": 0.02, "sparse_step_up": 0.05, "sparse_warmup_steps": 600, "stride": 8, "target_mask_density": 0.45, "use_c": 1, "use_c_exog": 1, "use_t": 1, "use_t_exog": 1, "weight_gate_floor": 0.03, "weight_gate_sharpness": 8.0}' --gpus 0 --num-workers 1 --timeout 60000 --save-path "maize_NL_NL11_daily_otb_meteo_plus_targets/SWAN_V3_TUNE_R1/h96_B"

echo "=== SWAN_V3 maize_NL_NL11_daily_meteo_plus_targets TUNE_R1 finished ==="
